export type RouteData = {
    routeName: string,
    mountainName: string,
    recommendedMonth: string[],
    routeType: string,
    altitudeZone: string[],
    elevationDifference: number,
    maxAltitude: number,
    minAltitude: number,
    totalDistance: number,
    elevationDistance: number,
    decentDistance: number,
    startPoint: string,
    endPoint: string,
    mapUrl: string,
    elevationChart: any,
    description: string,
    pictures : string[],
}